In [1]:
import sklearn

In [2]:
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.18.1.


In [3]:
col_names = ["duration","protocol_type","service","flag","src_bytes",
             "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
             "logged_in","num_compromised","root_shell","su_attempted","num_root","num_file_creations",
             "num_shells","num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count",
             "srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
             "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
             "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
             "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
             "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("kddcup.data_10_percent", header=None, names = col_names)

# 前処理
## カテゴリ化

In [6]:
data.label.value_counts()

smurf.              280790
neptune.            107201
normal.              97278
back.                 2203
satan.                1589
ipsweep.              1247
portsweep.            1040
warezclient.          1020
teardrop.              979
pod.                   264
nmap.                  231
guess_passwd.           53
buffer_overflow.        30
land.                   21
warezmaster.            20
imap.                   12
rootkit.                10
loadmodule.              9
ftp_write.               8
multihop.                7
phf.                     4
perl.                    3
spy.                     2
Name: label, dtype: int64

In [7]:
data['label2'] = data.label.where(data.label.str.contains('normal'),'atack')

In [8]:
data.label2.value_counts()

atack      396743
normal.     97278
Name: label2, dtype: int64

In [9]:
data['label3'] = data.label.copy()

In [10]:
data.loc[data.label.str.contains('back|land|neptune|pod|smurf|teardrop'),'label3'] = 'DoS'

In [11]:
data.loc[data.label.str.contains('buffer_overflow|loadmodule|perl|rootkit'),'label3'] = 'U2R'

In [12]:
data.loc[data.label.str.contains('ftp_write|guess_passwd|imap|multihop|phf|spy|warezclient|warezmaster'),'label3'] = 'R2L'

In [13]:
data.loc[data.label.str.contains('ipsweep|nmap|portsweep|satan'),'label3'] = 'Probe'

In [14]:
data.label3.value_counts()

DoS        391458
normal.     97278
Probe        4107
R2L          1126
U2R            52
Name: label3, dtype: int64

## 数値化

In [15]:
 from sklearn import preprocessing

In [16]:
le_protocol_type = preprocessing.LabelEncoder()

In [17]:
le_protocol_type.fit(data.protocol_type)

LabelEncoder()

In [18]:
data.protocol_type=le_protocol_type.transform(data.protocol_type)

In [19]:
le_service = preprocessing.LabelEncoder()

In [20]:
le_service.fit(data.service)

LabelEncoder()

In [21]:
data.service = le_service.transform(data.service)

In [22]:
le_flag = preprocessing.LabelEncoder()

In [23]:
le_flag.fit(data.flag)

LabelEncoder()

In [24]:
data.flag = le_flag.transform(data.flag)

In [25]:
data.describe()

duration  protocol_type        service           flag  \
count  494021.000000  494021.000000  494021.000000  494021.000000   
mean       47.979302       0.467132      23.408894       7.842446   
std       707.746472       0.575606      13.538332       2.250853   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000      14.000000       9.000000   
50%         0.000000       0.000000      14.000000       9.000000   
75%         0.000000       1.000000      42.000000       9.000000   
max     58329.000000       2.000000      65.000000      10.000000   

          src_bytes     dst_bytes           land  wrong_fragment  \
count  4.940210e+05  4.940210e+05  494021.000000   494021.000000   
mean   3.025610e+03  8.685324e+02       0.000045        0.006433   
std    9.882181e+05  3.304000e+04       0.006673        0.134805   
min    0.000000e+00  0.000000e+00       0.000000        0.000000   
25%    4.500000e+01  0.000000e+00       0.000000        0.000000   
50%    5.200000e+02  0.000000e+00       0.000000        0.000000   
75%    1.032000e+03  0.000000e+00       0.000000        0.000000   
max    6.933756e+08  5.155468e+06       1.000000        3.000000   

              urgent            hot            ...             dst_host_count  \
count  494021.000000  494021.000000            ...              494021.000000   
mean        0.000014       0.034519            ...                 232.470778   
std         0.005510       0.782103            ...                  64.745380   
min         0.000000       0.000000            ...                   0.000000   
25%         0.000000       0.000000            ...                 255.000000   
50%         0.000000       0.000000            ...                 255.000000   
75%         0.000000       0.000000            ...                 255.000000   
max         3.000000      30.000000            ...                 255.000000   

       dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count       494021.000000           494021.000000           494021.000000   
mean           188.665670                0.753780                0.030906   
std            106.040437                0.410781                0.109259   
min              0.000000                0.000000                0.000000   
25%             46.000000                0.410000                0.000000   
50%            255.000000                1.000000                0.000000   
75%            255.000000                1.000000                0.040000   
max            255.000000                1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                494021.000000                494021.000000   
mean                      0.601935                     0.006684   
std                       0.481309                     0.042133   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       1.000000                     0.000000   
75%                       1.000000                     0.000000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count         494021.000000             494021.000000         494021.000000   
mean               0.176754                  0.176443              0.058118   
std                0.380593                  0.380919              0.230590   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                0.000000                  0.000000              0.000000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
cou

In [26]:
from sklearn.externals import joblib

In [27]:
#joblib.dump(data,'dump/20171115/data.pkl')

In [28]:
data = joblib.load('dump/20171115/data.pkl')

In [29]:
data.shape

(494021, 44)

In [31]:
from sklearn.utils import resample
tmp = resample(data,n_samples=500,random_state=0)

## ラベルの分離

In [32]:
y_train_1 = tmp.label.copy() 

In [33]:
y_train_2 = tmp.label2.copy()

In [34]:
y_train_3 = tmp.label3.copy()

In [35]:
x_train = tmp.drop(['label','label2','label3'],axis=1)

In [36]:
x_train.shape

(500, 41)

## 標準化

In [37]:
ss = preprocessing.StandardScaler()

In [38]:
ss.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [39]:
x_train = ss.transform(x_train)

In [40]:
col_names2 = ["duration","protocol_type","service","flag","src_bytes",
             "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
             "logged_in","num_compromised","root_shell","su_attempted","num_root","num_file_creations",
             "num_shells","num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count",
             "srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
             "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
             "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
             "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
             "dst_host_rerror_rate","dst_host_srv_rerror_rate"]

In [41]:
pd.DataFrame(x_train,columns=col_names2).describe()

duration  protocol_type       service          flag     src_bytes  \
count  5.000000e+02   5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   1.292300e-16  -6.661338e-19  2.358114e-16 -1.643130e-17 -1.055822e-16   
std    1.001002e+00   1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -7.598988e-02  -8.072074e-01 -1.500989e+00 -3.035655e+00 -6.412025e-01   
25%   -7.598988e-02  -8.072074e-01 -6.890851e-01  5.241867e-01 -6.184169e-01   
50%   -7.598988e-02  -8.072074e-01 -6.890851e-01  5.241867e-01 -1.370103e-01   
75%   -7.598988e-02   8.744746e-01  1.599008e+00  5.241867e-01  3.594250e-01   
max    1.889767e+01   2.556157e+00  2.115674e+00  5.241867e-01  1.498391e+01   

          dst_bytes   land  wrong_fragment  urgent           hot  \
count  5.000000e+02  500.0    5.000000e+02   500.0  5.000000e+02   
mean  -4.440892e-19    0.0    8.032464e-17     0.0  2.241263e-16   
std    1.001002e+00    0.0    1.001002e+00     0.0  1.001002e+00   
min   -8.163295e-02    0.0   -6.337243e-02     0.0 -4.476615e-02   
25%   -8.163295e-02    0.0   -6.337243e-02     0.0 -4.476615e-02   
50%   -8.163295e-02    0.0   -6.337243e-02     0.0 -4.476615e-02   
75%   -8.163295e-02    0.0   -6.337243e-02     0.0 -4.476615e-02   
max    2.163352e+01    0.0    1.577973e+01     0.0  2.233831e+01   

                 ...             dst_host_count  dst_host_srv_count  \
count            ...               5.000000e+02        5.000000e+02   
mean             ...              -6.838974e-17       -1.687539e-17   
std              ...               1.001002e+00        1.001002e+00   
min              ...              -3.572501e+00       -1.731350e+00   
25%              ...               3.541737e-01       -1.525524e+00   
50%              ...               3.541737e-01        6.450016e-01   
75%              ...               3.541737e-01        6.450016e-01   
max              ...               3.541737e-01        6.450016e-01   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count            5.000000e+02            5.000000e+02   
mean             1.063594e-16            7.305268e-17   
std              1.001002e+00            1.001002e+00   
min             -1.784623e+00           -2.835301e-01   
25%             -1.339982e+00           -2.835301e-01   
50%              6.188450e-01           -2.835301e-01   
75%              6.188450e-01            1.122406e-01   
max              6.188450e-01            7.631884e+00   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                 5.000000e+02                 5.000000e+02   
mean                  2.249312e-16                 5.362377e-17   
std                   1.001002e+00                 1.001002e+00   
min                  -1.280049e+00                -1.786072e-01   
25%                  -1.280049e+00                -1.786072e-01   
50%                   8.111246e-01                -1.786072e-01   
75%                   8.111246e-01                -1.786072e-01   
max                   8.111246e-01                 1.095651e+01   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count          5.000000e+02              5.000000e+02          5.000000e+02   
mean          -6.727952e-17              1.978417e-16          6.417089e-17   
std            1.001002e+00              1.001002e+00          1.001002e+00   
min           -4.749996e-01             -4.721328e-01         -2.531551e-01   
25%           -4.749996e-01             -4.721328e-01         -2.531551e-01   
50%           -4.749996e-01             -4.721328e-01         -2.531551e-01   
75%           -4.749996e-01             -4.721328e-01         -2.531551e-01   
max            2.119209e+00              2.120009e+00          4.039064e+00   

       dst_host_srv_rerror_rate  
count              5.000000e+02  
mean              -1.000311e-16  
std                1.001002e+00  
min               -2.486719e-01  
25%               -2.486719e-01  
50%

In [42]:
#joblib.dump(x_train,'dump/20171115/x_train.pkl')

In [43]:
#joblib.dump(y_train_1,'dump/20171115/y_train_1.pkl')

In [44]:
#joblib.dump(y_train_2,'dump/20171115/y_train_2.pkl')

In [45]:
#joblib.dump(y_train_3,'dump/20171115/y_train_3.pkl')

## 予備学習

In [46]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
import numpy as np

In [47]:
tuned_parameters = {
    "pca__n_components" : list(range(2, 6)),
    'svm__kernel' : ["linear", "poly", "rbf", "sigmoid"],
    'svm__C' : np.logspace(0, 2, 5),
    'svm__gamma' : np.logspace(-3, 0, 5)
}
    

In [48]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
     ('pca', PCA()),
        ('svm', SVC())])

In [49]:
score = 'f1'
clf = GridSearchCV(
    pipeline,
    tuned_parameters, 
    cv=5, 
    scoring='%s_weighted' % score ) 

In [50]:
#import warnings
#warnings.filterwarnings('ignore')
clf.fit(x_train, y_train_2)

/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predic

GridSearchCV(cv=5, error_score='raise',
       estimator=Pipeline(steps=[('pca', PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svm', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))]),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'pca__n_components': [2, 3, 4, 5], 'svm__kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'svm__C': array([   1.     ,    3.16228,   10.     ,   31.62278,  100.     ]), 'svm__gamma': array([ 0.001  ,  0.00562,  0.03162,  0.17783,  1.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='f1_weighted', verbose=0)

In [51]:
clf.best_score_

0.99409442984551677

In [52]:
clf.best_estimator_

Pipeline(steps=[('pca', PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svm', SVC(C=10.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=1.0, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [53]:
import time
t1=time.perf_counter()
pred=clf.predict(x_train)
t2=time.perf_counter()

In [54]:
print(t2-t1,"秒")

0.001309432999960336 秒


In [55]:
from sklearn.metrics import confusion_matrix, classification_report

In [56]:
print(classification_report(y_train_2, pred))
print(confusion_matrix(y_train_2, pred))

             precision    recall  f1-score   support

      atack       1.00      1.00      1.00       405
    normal.       0.98      1.00      0.99        95

avg / total       1.00      1.00      1.00       500

[[403   2]
 [  0  95]]


## 予備学習

In [57]:
pipeline = Pipeline([
     ('pca', PCA()),
        ('svm', SVC())])

In [58]:
score = 'f1'
clf = GridSearchCV(
    pipeline,
    tuned_parameters, 
    cv=5, 
    scoring='%s_weighted' % score ) 

In [59]:
clf.fit(x_train, y_train_3)

/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined an

GridSearchCV(cv=5, error_score='raise',
       estimator=Pipeline(steps=[('pca', PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svm', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))]),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'pca__n_components': [2, 3, 4, 5], 'svm__kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'svm__C': array([   1.     ,    3.16228,   10.     ,   31.62278,  100.     ]), 'svm__gamma': array([ 0.001  ,  0.00562,  0.03162,  0.17783,  1.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='f1_weighted', verbose=0)

In [60]:
clf.best_score_

0.9930641842234198

In [61]:
clf.best_estimator_

Pipeline(steps=[('pca', PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svm', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.17782794100389229,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False))])

In [62]:
t1=time.perf_counter()
pred=clf.predict(x_train)
t2=time.perf_counter()

In [63]:
print(t2-t1,"秒")

0.0014936960000113686 秒


In [64]:
print(classification_report(y_train_2, pred))
print(confusion_matrix(y_train_3, pred))

             precision    recall  f1-score   support

        DoS       1.00      0.99      1.00       397
      Probe       1.00      1.00      1.00         7
        R2L       0.00      0.00      0.00         1
    normal.       0.97      1.00      0.98        95

avg / total       0.99      0.99      0.99       500

[[395   0   0   2]
 [  0   7   0   0]
 [  0   0   0   1]
 [  0   0   0  95]]


/Users/mhaya/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
